"use client";

import React from "react";
import { ScrollReveal } from "@/components/ScrollReveal";

export function CoInvestment() {
    return (
        <section id="why-partner" className="py-24 relative">
            <div className="max-w-7xl mx-auto px-4 md:px-6">
                <ScrollReveal>
                    <div className="mb-16">
                        <span className="block text-[#B066FF] font-mono text-xs tracking-widest mb-6 uppercase">
                            003 / Why Co-Investment
                        </span>
                        <h2 className="text-4xl md:text-5xl font-display leading-tight mb-8">
                            Alpha beyond the backtest.
                        </h2>
                        <div className="max-w-2xl text-zinc-200 font-sans leading-relaxed space-y-4">
                            <p>
                                Real alpha survives execution costs, market impact, and regime shifts. Our partnership model aligns our incentives with your net P&L, not your data budget.
                            </p>
                            <p>
                                We deploy novel graph-based signals directly into your execution environment. It&apos;s not just a data feed; it&apos;s a co-managed strategy component built to perform.
                            </p>
                        </div>
                    </div>

                    <div className="grid md:grid-cols-3 gap-6">
                        {/* Card 1 */}
                        <div className="bg-[#151725] border border-white/5 p-8 hover:bg-[#1A1C2A] transition-colors duration-300">
                            <span className="block text-[#B066FF] font-mono text-xs uppercase mb-4 tracking-wider">01 · Signal</span>
                            <h3 className="text-xl font-display text-white mb-3">Uncorrelated Alpha</h3>
                            <p className="text-zinc-300 text-sm leading-relaxed">
                                Deploy signals derived from graph topology—relationship breakdowns, contagion, and flow—that provide orthogonality to standard momentum or mean-reversion factors.
                            </p>
                        </div>

                        {/* Card 2 */}
                        <div className="bg-[#151725] border border-white/5 p-8 hover:bg-[#1A1C2A] transition-colors duration-300">
                            <span className="block text-[#B066FF] font-mono text-xs uppercase mb-4 tracking-wider">02 · Validation</span>
                            <h3 className="text-xl font-display text-white mb-3">Execution Loops</h3>
                            <p className="text-zinc-300 text-sm leading-relaxed">
                                Data vendors deliver csvs and disappear. We optimize for your fills. Feedback from live execution drives our continuous model retraining and parameter tuning.
                            </p>
                        </div>

                        {/* Card 3 */}
                        <div className="bg-[#151725] border border-white/5 p-8 hover:bg-[#1A1C2A] transition-colors duration-300">
                            <span className="block text-[#B066FF] font-mono text-xs uppercase mb-4 tracking-wider">03 · Structure</span>
                            <h3 className="text-xl font-display text-white mb-3">Asymmetric Upside</h3>
                            <p className="text-zinc-300 text-sm leading-relaxed">
                                No management fees. We only monetize net new P&L generated by our signals. A pure performance partnership.

                            </p>
                        </div>
                    </div>
                </ScrollReveal>
            </div>
        </section>
    );
}
